export const GET_PROFILE_REQUEST = 'profile/GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'profile/GET_PROFILES_SUCCESS'
export const GET_PROFILE_FAILED = 'profile/GET_PROFILES_FAILED'

export const SUBMIT_PROFILE_REQUEST = 'profile/SUBMIT_PROFILE_REQUEST'
export const SUBMIT_PROFILE_SUCCESS = 'profile/SUBMIT_PROFILES_SUCCESS'
export const SUBMIT_PROFILE_FAILED = 'profile/SUBMIT_PROFILES_FAILED'

export const CHANGE_PASSWORD_REQUEST = 'profile/CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'profile/CHANGE_PASSWORDS_SUCCESS'
export const CHANGE_PASSWORD_FAILED = 'profile/CHANGE_PASSWORDS_FAILED'
