image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  only:
    - dev
  tags:
    - dev
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t registry.service.zagora/media/map-projects:dev --rm=true .
  - docker push registry.service.zagora/media/map-projects:dev
